Budget app
Uzair-Manzoor/budget_app pull request #2
Opened 2024-01-26 16:02 UTC by Uzair-Manzoor

## This pull request has been created against below mentioned amendments into the project as per previous viewer's feedback:

- [x] Fixed issue with the create method to work as expected. Previously, It was crashing the app when user tried to add a category and was complaining about the icon being passed into it. The feature has been updated so the category can be created successfully and other features are testable.

2024-01-26 17:01 UTC, julie-ify requested changes
## Hi @Uzair-Manzoor,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- App layout follows Behance design ✔️ 
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly record a presentation of your app and provide the link in the readme file

- [ ] Kindly ensure your live demo is functional. When I try click the sign up button on the splash button to sign a user, the app throws error. Kindly fix the live demo app.

  ![image](https://github.com/Uzair-Manzoor/budget_app/assets/81468675/098c500b-9b18-4f6d-b10b-fb71bacdff17)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-27 06:55 UTC, binhussen requested changes
Hi @Uzair-Manzoor , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- Sticked the given design ✔️
- Well stractured Code ✔️
- Used Git flow ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-27 06:55 UTC, binhussen commented on README.md
>  - [Live Demo Link]()
- Kindly, having the online version is not optional, please fix what the previous reviewer suggested and add it to fit the requirement and have better user accessibility :+1:  
![2024-01-27_09-47](https://github.com/Uzair-Manzoor/budget_app/assets/52010789/917d352d-4f10-47b0-958f-03740f19c9ef)

2024-01-27 06:55 UTC, binhussen commented on README.md
> +- [Presentation Link](https://www.loom.com/share/e06a206fb2d1466589eff6f915bede6d?sid=6ab2daed-7b7b-430b-b754-df37d89cc538)
- Great job for adding the clear video presentation, I think you forgot to  highlight some interesting pieces of code as mentioned in the requirmnet :+1: 
![2024-01-27_09-52](https://github.com/Uzair-Manzoor/budget_app/assets/52010789/d1494b58-fd8f-430a-8d8f-7aa563a87955)

2024-01-27 12:05 UTC, AmaduKamara approved these changes
# Status: APPROVED 🟢 🟢 🟢

Hi @Uzair-Manzoor,

Good job working on the changes highlighted by the previous reviewer 👍🏽

Your project is complete! There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You set up Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Implement Signup and Login functionalities correctly 👍🏽
✅ Categories and Transactions are created successfully as expected 👍🏽
✅ Good descriptive README file 👍🏽
✅ Implemented tests correctly and all test cases passed 👍🏽
✅ The app works fine on the local server and the deployed one as well 👍🏽

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2024-01-27 12:12 UTC, merged